name: Maven Dependency Tree Dependency Submission
description: A GitHub Action for Maven project to submit a complete dependency tree to populate the GitHub Dependency Graph

branding:
  icon: alert-triangle
  color: red

inputs:
  directory:
    description: The directory that contains the maven project
    type: string
    default: ${{ github.workspace }}

  settings-file:
    description: Optional path to a Maven settings.xml file for the dependencies to be resolved
    type: string

  ignore-maven-wrapper:
    description: Flag for optionally ignoring any maven wrapper files (mvnw) and instead rely on the PATH provided mvn
    type: boolean
    default: false

  maven-args:
    description: Additional maven arguments to add to the command line invocation of maven when it generates the dependency snapshot
    type: string
    default: ''

  token:
    description: The GitHub token to use to submit the depedency snapshot to the repository
    type: string
    default: ${{ github.token }}

  github-api-url:
    description: The URL to the GitHub API to use to publish the results to, defaults to reading this from the Actions environment
    type: string
    required: false

runs:
  using: node16
  main: dist/index.js
